version: '3.8'

services:
  # Zookeeper Service
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"  # Zookeeper port
    networks:
      - stream-network

  # Kafka Service
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    ports:
      - "9092:9092"  # Kafka broker port
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - stream-network

  # Hadoop NameNode Service
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # NameNode RPC
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - stream-network

  # Hadoop DataNode Service
  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode
    networks:
      - stream-network

  # YARN ResourceManager Service
  yarn-resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn-resourcemanager
    ports:
      - "8088:8088"  # ResourceManager Web UI
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=yarn-resourcemanager
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - YARN_CONF_yarn_resourcemanager_address=yarn-resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_webapp_address=yarn-resourcemanager:8088
    depends_on:
      - hadoop-namenode
      - hadoop-datanode
    networks:
      - stream-network

  # YARN NodeManager Service
  yarn-nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn-nodemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=yarn-resourcemanager
    depends_on:
      - yarn-resourcemanager
      - hadoop-namenode
      - hadoop-datanode
    networks:
      - stream-network

  # HBase Master Service
  hbase-master:
    image: dajobe/hbase
    container_name: hbase-master
    ports:
      - "16000:16000"  # HBase Master RPC
      - "16010:16010"  # HBase Master Web UI
      - "16020:16020"  # HBase RegionServer RPC
      - "16030:16030"  # HBase RegionServer Web UI
    environment:
      - HBASE_MANAGES_ZK=true
      - ZOOKEEPER_QUORUM=zookeeper
    depends_on:
      - zookeeper
      - hadoop-namenode
      - hadoop-datanode
    networks:
      - stream-network

  # HBase Thrift Server Service
  hbase-thrift:
    image: iwan0/hbase-thrift-standalone
    container_name: hbase-thrift
    ports:
      - "9090:9090"  # HBase Thrift Server
    environment:
      - HBASE_ZOOKEEPER_QUORUM=zookeeper
      - HBASE_ZOOKEEPER_CLIENT_PORT=2181
    depends_on:
      - hbase-master
    networks:
      - stream-network


networks:
  stream-network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
