FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        libc6-dev \
        python3-dev && \
    rm -rf /var/lib/apt/lists/*

COPY Stream_layer/requirements.stream.txt .
RUN pip install -r requirements.stream.txt

COPY . .

CMD ["python", "-u", "Stream_layer/stream_pipeline.py"]